### ISSUE TITLE
Include internal modules

### ISSUE THREAD

**Issue by jonathandion** [ryanwmarsh/sam-with-npm#1]
Is it possible to have an imported module using `npm pack` ?

e.g: package `a` import `core`
```
`-- packages
    |-- core
    |   |-- index.js
    |   `-- package.json
    |-- a
    |   `-- package.json
    `-- b
        |-- index.js // import core
        |-- package-lock.json
        |-- package.json
        `-- package.zip
```

**Comment by ryanwmarsh** [comment]
Yes if you do a relative install. If you try to use `npm link` good luck. I've had nothing but trouble with that, in general. 

Let's say you wanted to import `core` into `a`

```bash
cd a
npm install --save -B ../core
npm pack
```
